### ISSUE TITLE
How to split lines?

### ISSUE THREAD

**Issue by Thieund** [JungWinter/split#15] opened 2022-02-22 04:57 UTC
Which value should I put into "seperator" to split a file content into lines?

**Comment by winterjung** [comment] 2022-02-22 05:22
@Thieund Hi! Could you try sep**a**rator with `"\n"`? (In `@v2`, `sep`**`e`**`rator` input is renamed to `sep`**`a`**`rator`

```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: 'something\nmulti line texts you want'
          separator: '\n'
```

**Comment by Thieund** [comment] 2022-02-22 06:50
Hi @JungWinter,
I have tried to used '\n', '\r\n' but it could not split file content which has carriage returns in it. 
![image](https://user-images.githubusercontent.com/14900487/155078062-467c5124-c7e5-488c-bbf5-7d3891066b70.png)

btw, I can only set the value to seperator, setting separator did not have any affect.

**Comment by winterjung** [comment] 2022-02-22 14:34
Could you provide the actions or steps you tried? I'll reproduce and test it :)

**Comment by Thieund** [comment] 2022-02-23 02:31
I just read content of an .env file containing following lines:
REPLICA_POSTGRES_PORT=5432
REPLICA_POSTGRES_SSL=true
and then using seperator '/n' or '/r/n' to split it into lines but did not work.

**Comment by winterjung** [comment] 2022-03-13 13:36
@Thieund Sorry for late respnding. Unfortunately I can't reproduce problem. When I add test cases like below, It was passed so I'm not sure which to look further into. Could you give me more information how to read that crlf file and pass to `split` actions?

```diff
@pytest.mark.parametrize(
    'msg, sep, expected',
    [
        ('/release split v1.0.0', ' ', ['/release', 'split', 'v1.0.0']),
        ('/release split v1.0.0', ',', ['/release split v1.0.0']),
        ('/release split v1.0.0', '.', ['/release split v1', '0', '0']),
        ('/release split v1', '\'', ['/release split v1']),
        ('/release split v1', '"', ['/release split v1']),
        ('/release split v1', '/', ['', 'release split v1']),
        ('/release  split  v1', ' ', ['/release', '', 'split', '', 'v1']),
        (' /release split v1 ', ' ', ['', '/release', 'split', 'v1', '']),
+       ('a\r\nb', '\r\n', ['a', 'b']),
+       ('a\r\nb', '\n', ['a\r', 'b']),
    ],
)
def test_separator(self, msg, sep, expected):
    assert split(msg, sep=sep) == expected
```

**Comment by winterjung** [comment] 2023-03-13 03:53
I tested `split@v2.1.1-rc1`(almost same with `v2` and `v2.1.0`) on `ubuntu-18.04` and it worked intentionally with `'\r\n'`. But [when tested on `windows-2022`](https://github.com/JungWinter/split/actions/runs/4401195122/jobs/7707170911), I got the error because container action is only supported on Linux.

I don't think the original issue is related to the hosting environment, so I'm closing this issue. If you still encounter any issues, please let me know. :)

**Closed as not planned by winterjung** 2023-03-13 03:53 UTC
