### ISSUE TITLE
Input not splitted

### ISSUE THREAD

**Issue by RedBrumbler** [JungWinter/split#8] opened 2021-09-23 10:03 UTC
it might just be me but my input, ${{ github.repository }} (so in this instance `RedBrumbler/MonkeComputer`) is not being split with separator /

[Action illustrating this issue](https://github.com/RedBrumbler/MonkeComputer/runs/3685772107?check_suite_focus=true)

as seen in the log the input is indeed RedBrumbler/MonkeComputer and separator / but in the following echo _0 contains the full string and _1 contains nothing.

Any pointers as to why this happens would be appreciated, or any ideas on how to get the current repo owner as a string is welcome too

**Comment by RedBrumbler** [comment] 2021-09-23 10:04
Image illustrating the logs

![afbeelding](https://user-images.githubusercontent.com/51795403/134489203-e211e01c-8831-47a5-a787-80d815e3e456.png)

**Comment by RedBrumbler** [comment] 2021-09-23 10:04
[And the used workflow file](https://github.com/RedBrumbler/MonkeComputer/actions/runs/1265318563/workflow)

**Comment by winterjung** [comment] 2021-09-23 10:58
Thanks for the reporting. It seems like unintended behavior.

I think [this docker image tag in action.yml](https://github.com/JungWinter/split/blob/bf0511dd1e207c86033a11f175f808f9fa77f717/action.yml#L223) causes the error.

<img src="https://user-images.githubusercontent.com/13811604/134495472-d725d764-a2f1-4fd5-8f8e-ad6cb7f15f4d.png" width="500" />
<div align="left"><sup><strong><a href="https://hub.docker.com/repository/docker/winterjung/split">winterjung/split docker hub: </a></strong>never pulled</sup></div>

I'll investigate how to versioning in `action.yml`

**Comment by winterjung** [comment] 2021-09-23 12:18
I think it's resovled from #9 pr. If it's still occurred, please report anytime! thx

**Comment by winterjung** [comment] 2021-09-25 05:39
Rollbacked by #11 issue. I'll fix this again soon

**Comment by heanzyzabala** [comment] 2021-11-21 07:13
@JungWinter Any updates on this?

**Comment by winterjung** [comment] 2021-11-22 05:40
@heanzyzabala Sorry for delay to resolve this issue. I'll try to fix as soon as possible. Thanks to ping me :)

**Comment by winterjung** [comment] 2021-12-05 05:14
@heanzyzabala @RedBrumbler I think the issue has been fixed by updating action.yml to use latest docker image tag. Feel free to report if it's not fixed. thx!

**Closed as completed by winterjung** 2021-12-05 05:14 UTC
